public enum EWallTileType
{
    Up,
    Right,
    Down,
    Left,
    InnerCornerDownRight,
    InnerCornerDownLeft,
    DiagonalCornerUpRight,
    DiagonalCornerUpLeft,
    DiagonalCornerDownRight,
    DiagonalCornerDownLeft,
    Full,
    FullEightDirections,
    BottomEightDirections,
    UpDown,
    RightLeft,
    UUp,
    URight,
    UDown,
    ULeft
}
